Repository laudio/pyodbc, pull requests merged in 2019-12, with the labels that each got.

#35 Support MySQL and add test to verify database connection
  .env.example
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  test/test_connection.py
  test/util.py
Labels: mysql, test

#37 Increase sleep time to wait for database servers
  .travis.yml
Labels: test

#38 Integrate pylint in the CI and build process
  .pylintrc
  .travis.yml
  Dockerfile
  Makefile
  examples/app-mssql/main.py
  examples/app-mssql/requirements.txt
  examples/app-pg/main.py
  examples/app-pg/requirements.txt
  examples/data-transfer-mssql/main.py
  examples/data-transfer-pg/main.py
  requirements-dev.txt
Labels: ci

#34 Basic type hinting for functions and global variables
  examples/app-mssql/main.py
  examples/app-pg/main.py
  examples/data-transfer-mssql/main.py
  examples/data-transfer-pg/main.py
  test/test_mssql.py
  test/test_mysql.py
  test/test_pg.py
  test/util.py
Labels: static typing, types, wip

#41 Add simple example project using MySQL
  README.md
  examples/app-mysql/.env.example
  examples/app-mysql/Dockerfile
  examples/app-mysql/README.md
  examples/app-mysql/docker-compose.yml
  examples/app-mysql/main.py
  examples/app-mysql/requirements.txt
Labels: example, mysql

#43 Add data-transfer-mysql example project
  README.md
  examples/data-transfer-mysql/.env.example
  examples/data-transfer-mysql/Dockerfile
  examples/data-transfer-mysql/README.md
  examples/data-transfer-mysql/docker-compose.yml
  examples/data-transfer-mysql/main.py
  examples/data-transfer-mysql/requirements.txt
  examples/data-transfer-mysql/sql/dest_db_setup.sql
  examples/data-transfer-mysql/sql/source_db_setup.sql
Labels: data transfer, example, mysql

#44 Bump pyodbc to 4.0.28
  requirements.txt
Labels: dependencies
